# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: sensoconsultoria.github.io
title: Home
email: sensocursos@gmail.com
author: Senso
description: Consultoria estatística 
 
copyright: 'Copyright &copy; 2016 Senso. All Rights Reserved.'
credits: 'Credits: Bootstrap theme created by <a href="http://startbootstrap.com/">Start Bootstrap</a>.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:

  - title: facebook 
    url: https://www.facebook.com
  - title: envelope
    url: mailto:sensocursos@gmail.com

